# Generated by Django 4.2.7 on 2023-12-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_address_account_instagram_account_telegram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
