# Generated by Django 4.2.7 on 2023-12-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['name'], 'verbose_name': 'Страница обратной связи', 'verbose_name_plural': 'Страница обратной связи'},
        ),
    ]
