# Generated by Django 4.2.7 on 2023-12-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_contactform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
