# Generated by Django 4.2.7 on 2023-12-10 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('E', 'Экономика'), ('S', 'Наука'), ('IT', 'IT'), ('SP', 'Спорт'), ('N', 'Природа'), ('W', 'Мировые новости'), ('R', 'Региональные новости')], max_length=20, verbose_name='Категория'),
        ),
    ]
