# Generated by Django 4.2.7 on 2023-12-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('E', 'Экономика'), ('S', 'Наука'), ('IT', 'IT'), ('SP', 'Спорт'), ('N', 'Природа'), ('W', 'Мировые новости'), ('R', 'Региональные новости'), ('C', 'Культура'), ('R', 'Региональные новости')], max_length=20, verbose_name='Категория'),
        ),
    ]
