# Generated by Django 4.2.7 on 2023-12-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_image_article_alter_image_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Картинка новости', 'verbose_name_plural': 'Картинки новостей'},
        ),
    ]
