# Generated by Django 4.2.7 on 2023-12-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_viewcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcount',
            options={'verbose_name': 'Просмотры новости', 'verbose_name_plural': 'Просмотры новостей'},
        ),
        migrations.RemoveIndex(
            model_name='viewcount',
            name='news_viewco_view_da_c81d57_idx',
        ),
    ]
