"""
Django settings for newsportal project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
# import environ

# переменная для подключения env файла
# env = environ.Env()
# environ.Env.read_env()

# защита вебхука
# sc = env('SECRET_KEY')
# GITHUB_WEBHOOK_KEY='lmNA5HynZsNSkJ8GCeY1rm8j7Gy2YWLJPtoM4X8lIxRlUj8yKC'  # - в env файл и в гит добавить
# GITHUB_WEBHOOK_KEY = env('GITHUB_WEBHOOK_KEY')



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-josyr_bops(pgr4asf-1ybj36&_(fz=9b_pufa=q&1vwaqn*n@'

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env("SECRET_KEY") #'django-insecure-josyr_bops(pgr4asf-1ybj36&_(fz=9b_pufa=q&1vwaqn*n@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # - при деплое сделав collectstatic
# DEBUG = True

ALLOWED_HOSTS = ['eh0388pe.pythonanywhere.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'news',
    'users',
    'bootstrap5',
    'debug_toolbar',
    'crispy_forms',
    'crispy_bootstrap5',
    'profanity',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware', # модуль мультиязычности
]




INTERNAL_IPS = ['127.0.0.1',]
ROOT_URLCONF = 'newsportal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newsportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eh0388pe$newsportal',
        'USER': 'eh0388pe',
        'PASSWORD': 'xc3pМq0Wt5da8s',
        'HOST': 'eh0388pe.mysql.pythonanywhere-services.com',
    }
}

# вариант с env
# DATABASES = {
#     'default': {
#         'ENGINE': env("DB_ENGINE")           #'django.db.backends.mysql',
#         'NAME': env("DB_NAME")               #'eh0388pe$newsportal',
#         'USER': env("DB_USERY")              #'eh0388pe',
#         'PASSWORD': env("DB_PASSWORD")       #'xc3pМq0Wt5da8s',
#         'HOST': env("DB_HOST")               #'eh0388pe.mysql.pythonanywhere-services.com',
#     }
# }


# PG вариант 2 нет доступа к БД со стороны python anywhere доступ к внещке закрыт, только белый список
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'newsportal',
#         'USER': 'newsportal_user',
#         'PASSWORD': 'ErFlROsHpj14',
#         'HOST': 'db.gwymkkqdlspoteuyfpur.supabase.co',
#         'PORT': '5432',
#         'OPTIONS': {'sslmode': 'require'},
#     }
# }

# нет доступа к БД со стороны python anywhere
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'newsportal',
#         'USER': 'newsportal_user',
#         'PASSWORD': 'ErFlROsHpj14',
#         'HOST': 'ep-orange-snow-03537423.ap-southeast-1.aws.neon.tech',
#         'PORT': '5432',
#         'OPTIONS': {'sslmode': 'require'},
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'
LANGUAGES = [
    ('ru', ('Russian')),
    ('en', ('English')),
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "static"     # заполнить для collectstaic

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATES_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = "news"
# LOGOUT_REDIRECT_URL = "news"  #перенаправляется после выхода, а не тут

LOGIN_URL = 'login'